### ISSUE TITLE
Thumbnail is still uploaded when main file exceeds max size

### ISSUE THREAD

**Issue by alvin** [jamgold/cropuploader#2]
This populates the s3/derivatives area with files that aren't in the database, and are thus orphaned.

I'm not using the cropper yet, just the uploader.

**Comment by jamgold** [comment]
That is a problem. Will fix that.

**Comment by alvin** [comment]
Awesome, thanks!

**Comment by jamgold** [comment]
You can check out the current master where I fixed the issue, I believe

**Comment by alvin** [comment]
Yup, works great.  Thanks so much!
