### ISSUE TITLE
Example not working because "release" file is missing

### ISSUE THREAD

**Issue by derwaldgeist** [jamgold/cropuploader#5]
Just wanted to inform you that your example folder does not work with Meteor out-of-the-box. It complains that the "release" file is missing. Not a big deal, but maybe you'd like to know about that.

Also, in the code that sets up the Slingshot directive, the following lines are missing:

``` js
    AWSAccessKeyId: Meteor.settings.awsAccessKeyId,
    AWSSecretAccessKey: Meteor.settings.awsSecretKey,
```

Without these credentials, Slingshot won't work.

Besides this, even if the app is running, it does not seem to do what is intended. I only see a file upload field and a button. But the upload itself is not working, and I can't see any image.

**Comment by jamgold** [comment]
Thank you. I will fix it.

**Comment by jamgold** [comment]
Pushed 0.0.4_1
