### ISSUE TITLE
.size() deprecated in jquery

### ISSUE THREAD

**Issue by jakim929** [jamgold/cropuploader#6]
Thanks for the great package. One issue: .size() for jquery selectors is deprecated, and it raises an error of "file.size is not a function" when I press the upload button.

**Comment by jamgold** [comment]
I will update the code and publish a new version

**Comment by jamgold** [comment]
Can you tell me **where** in the code you encountered this?

**Comment by jakim929** [comment]
'cropuploader-client.js' line 125. Not sure if there's issues elsewhere, but this is where the error gets raised for me

**Comment by jamgold** [comment]
Can't find it in the code, so must have fixed it a while ago. I just published 0.0.4_2
